-- Estrutura PostgreSQL para o Supabase.
-- Execute este arquivo no SQL Editor de um projeto novo.

create table public.especies (
  id bigint generated by default as identity primary key,
  nome_popular varchar(100) not null,
  nome_cientifico varchar(150) not null unique,
  familia varchar(100),
  classe varchar(100),
  status_conservacao varchar(100)
);

create table public.regioes (
  id bigint generated by default as identity primary key,
  nome varchar(100) not null,
  tipo_ecossistema varchar(100),
  latitude double precision,
  longitude double precision,
  descricao varchar(500)
);

create table public.observacoes (
  id bigint generated by default as identity primary key,
  data date not null,
  descricao text,
  foto_url varchar(255),
  especie_id bigint not null references public.especies(id) on delete restrict,
  regiao_id bigint not null references public.regioes(id) on delete restrict
);

alter table public.especies enable row level security;
alter table public.regioes enable row level security;
alter table public.observacoes enable row level security;

grant select, insert, update, delete on public.especies, public.regioes, public.observacoes to anon;
grant usage, select on all sequences in schema public to anon;

create policy "catálogo público" on public.especies
  for all to anon using (true) with check (true);
create policy "regiões públicas" on public.regioes
  for all to anon using (true) with check (true);
create policy "observações públicas" on public.observacoes
  for all to anon using (true) with check (true);
