-- Unified seed extracted from all submissions
-- Compatible with the supplied PostgreSQL/Supabase schema.
-- Execute only in an empty database created from that schema.
BEGIN;

INSERT INTO public.especies (id, nome_popular, nome_cientifico, familia, classe, status_conservacao)
VALUES
  (1, 'Barriguda', 'Cavanillesia umbellata', 'Malvaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (2, 'Mandacaru', 'Cereus jamacaru', 'Cactaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (3, 'Umbuzeiro', 'Spondias tuberosa', 'Anacardiaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (4, 'Araçá', 'Psidium cattleianum', 'Myrtaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (5, 'Siriguela', 'Spondias purpurea', 'Anacardiaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (6, 'Eucalipto', 'Eucalyptus sp.', 'Myrtaceae', 'Magnoliopsida', 'A preencher'),
  (7, 'Catingueira', 'Cenostigma pyramidale', 'Fabaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (8, 'Juazeiro', 'Ziziphus joazeiro', 'Rhamnaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (9, 'Espada-de-São-Jorge', 'Dracaena trifasciata', 'Asparagaceae', 'Liliopsida', 'Não avaliada'),
  (10, 'Algaroba', 'Prosopis juliflora', 'Fabaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (11, 'Sinzal', 'Agave sisalana', 'Asparagaceae', 'Liliopsida', 'Pouco preocupante'),
  (12, 'Palma-forrageira', 'Opuntia ficus-indica', 'Cactaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (13, 'Coqueiro', 'Cocos nucifera', 'Arecaceae', 'Liliopsida', 'Pouco preocupante'),
  (14, 'Licurizeiro', 'Syagrus coronata', 'Arecaceae', 'Liliopsida', 'Pouco preocupante'),
  (15, 'Árvore nim', 'Azadirachta indica', 'Meliaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (16, 'Amendoeira da praia', 'Terminalia catappa', 'Combretaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (17, 'Mamoeiro', 'Carica papaya', 'Caricaceae', 'Magnoliopsida', 'Dados insuficientes'),
  (18, 'Tomateiro', 'Solanum lycopersicum', 'Solanaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (19, 'Bananeira', 'Musa acuminata', 'Musaceae', 'Liliopsida', 'Pouco preocupante'),
  (20, 'Piolho-de-cobra', 'Diplopoda sp.', 'Spirostreptidae', 'Diplopoda', 'Conservada'),
  (21, 'Oliveira', 'Olea europaea', 'Oleaceae', 'Magnoliopsida', 'Conservada'),
  (22, 'Alamanda Roxa', 'Allamanda blanchetii', 'Apocynaceae', 'Magnoliopsida', 'Conservada'),
  (23, 'Rosa do Deserto', 'Adenium obesum', 'Apocynaceae', 'Magnoliopsida', 'Conservada'),
  (24, 'Bananeira', 'Musa spp', 'Musaceae', 'Liliopsida', 'Conservada'),
  (25, 'Palmeira-de-natal', 'Adonidia Merrilli', 'Arecaceae', 'Liliopsida', 'Conservada'),
  (26, 'Pau-brasil', 'Paubrasilia echinata', 'Fabaceae', 'Magnoliopsida', 'Em perigo'),
  (27, 'Mangueira', 'Mangifera indica L.', 'Anacardiaceae', 'Magnoliopsida', 'Conservada'),
  (28, 'Mamoeiro', 'Carica papaya L.', 'Caricaceae', 'Magnoliopsida', 'Conservada'),
  (29, 'Goiabeira', 'Psidium guajava', 'Myrtaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (30, 'Mangueira', 'Mangifera indica', 'Anacardiaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (31, 'Primavera ou Três-marias', 'Bougainvillea spectabilis', 'Nyctaginaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (32, 'Jabuticabeira / Jabuticaba', 'Plinia cauliflora', 'Myrtaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (33, 'Soldadinho-do-Araripe', 'Antilophia bokermanni', 'Pipridae', 'Aves', 'Criticamente em Perigo (CR)'),
  (34, 'Guigó-de-Caatinga', 'Callicebus barbarabrownae', 'Pitheciidae', 'Mammalia', 'Criticamente em Perigo (CR)'),
  (35, 'Cágado-do-Nordeste', 'Mesoclemmys tuberculata', 'Chelidae', 'Reptilia', 'Pouco Preocupante (LC)'),
  (36, 'Jararaca-da-seca', 'Bothrops erythromelas', 'Viperidae', 'Reptilia', 'Pouco Preocupante (LC)'),
  (37, 'Jabuti-piranga', 'Chelonoidis carbonarius', 'Testudinidae', 'Reptilia', 'Pouco Preocupante (LC)'),
  (38, 'Periquito-da-Caatinga', 'Eupsittula cactorum', 'Psittacidae', 'Aves', 'Pouco Preocupante (LC)'),
  (39, 'Carcará', 'Caracara plancus', 'Falconidae', 'Aves', 'Pouco Preocupante (LC)'),
  (40, 'Ararinha-azul', 'Cyanopsitta spixii', 'Psittacidae', 'Aves', 'Criticamente em Perigo (CR)'),
  (41, 'Teiú', 'Salvator merianae', 'Teiidae', 'Reptilia', 'Pouco Preocupante (LC)'),
  (42, 'Tatu-bola-do-Nordeste', 'Tolypeutes tricinctus', 'Chlamyphoridae', 'Mammalia', 'Em Perigo (EN)'),
  (43, 'Preá', 'Cavia aperea', 'Caviidae', 'Mammalia', 'Pouco Preocupante (LC)'),
  (44, 'Calango-de-cauda-verde', 'Ameiva ameiva', 'Teiidae', 'Reptilia', 'Pouco Preocupante (LC)'),
  (45, 'Cascavel', 'Crotalus durissus', 'Viperidae', 'Reptilia', 'Pouco Preocupante (LC)'),
  (46, 'Veado-catingueiro', 'Subulo gouazoubira', 'Cervidae', 'Mammalia', 'Pouco Preocupante (LC)'),
  (47, 'Asa-branca', 'Patagioenas picazuro', 'Columbidae', 'Aves', 'Pouco Preocupante (LC)'),
  (48, 'Boto-cor-de-rosa', 'Inia geoffrensis', 'Iniidae', 'Mammalia', 'Em Perigo (EN)'),
  (49, 'Lobo-guará', 'Chrysocyon brachyurus', 'Canidae', 'Mammalia', 'Vulnerável (VU)'),
  (50, 'Tamanduá-bandeira', 'Myrmecophaga tridactyla', 'Myrmecophagidae', 'Mammalia', 'Vulnerável (VU)'),
  (51, 'Xique-xique', 'Pilosocereus gounellei', 'Cactaceae', 'Magnoliopsida', 'Pouco Preocupante (LC)'),
  (52, 'Juazeiro', 'Sarcomphalus joazeiro', 'Rhamnaceae', 'Magnoliopsida', 'Pouco Preocupante (LC)'),
  (53, 'Oxalaia', 'Oxalaia quilombensis', 'Spinosauridae', 'Reptilia', 'Extinta'),
  (54, 'Palmatória (ou Quipá)', 'Tacinga palmadora', 'Cactaceae', 'Magnoliopsida', 'Pouco Preocupante'),
  (55, 'Jurema-branca', 'Mimosa artemisiana', 'Fabaceae', 'Magnoliopsida', 'Pouco Preocupante'),
  (56, 'Aroeira (Aroeira-do-sertão)', 'Myracrodruon urundeuva', 'Anacardiaceae', 'Magnoliopsida', 'Quase Ameaçada'),
  (57, 'Caroá', 'Neoglaziovia variegata', 'Bromeliaceae', 'Liliopsida', 'Pouco Preocupante'),
  (58, 'Gravatá', 'Bromelia laciniosa', 'Bromeliaceae', 'Liliopsida', 'Pouco Preocupante (LC)'),
  (59, 'Imburana-de-cheiro', 'Amburana cearensis', 'Fabaceae', 'Magnoliopsida', 'Em Perigo (EN)'),
  (60, 'Cedro-rosa', 'Cedrela fissilis', 'Meliaceae', 'Magnoliopsida', 'Vulnerável (VU)'),
  (61, 'Inco', 'Pityrocarpa moniliformis', 'Fabaceae', 'Magnoliopsida', 'Pouco Preocupante (LC)'),
  (62, 'Umbuzeiro', 'Spondias tuberosa Arruda', 'Anacardiaceae', 'Magnoliopsida', 'Pouco preocupante (LC)'),
  (63, 'Xique-xique', 'Xiquexique gounellei (F.A.C.Weber ex K.Schum.) Lavor & Calvente', 'Cactaceae', 'Magnoliopsida', 'Pouco preocupante (LC)'),
  (64, 'Macambira', 'Bromelia laciniosa Mart. ex Schult. & Schult.f.', 'Bromeliaceae', 'Liliopsida', 'Pouco preocupante (LC)'),
  (65, 'Juazeiro', 'Sarcomphalus joazeiro (Mart.) Hauenschild', 'Rhamnaceae', 'Magnoliopsida', 'Pouco preocupante (LC)'),
  (66, 'Moringa', 'Moringa oleifera Lam.', 'Moringaceae', 'Magnoliopsida', 'Pouco preocupante (LC)'),
  (67, 'Mandacaru', 'Cereus jamacaru DC.', 'Cactaceae', 'Magnoliopsida', 'Pouco preocupante (LC)'),
  (68, 'Algarobeira', 'Neltuma juliflora (Sw.) Raf.', 'Fabaceae', 'Magnoliopsida', 'Pouco preocupante (LC)'),
  (69, 'Quixabeira', 'Sideroxylon obtusifolium (Roem. & Schult.) T.D.Penn.', 'Sapotaceae', 'Magnoliopsida', 'Pouco preocupante (LC)'),
  (70, 'Pé de Acerola', 'Malpighia emarginata DC.', 'Malpighiaceae', 'Magnoliopsida', 'Não avaliada (NE)'),
  (71, 'Licurizeiro', 'Syagrus coronata (Mart.) Becc.', 'Arecaceae', 'Liliopsida', 'Pouco preocupante (LC)'),
  (72, 'Cachorro', 'Canis lupus familiaris', 'Canidae', 'Mammalia', 'Não Avaliado (NE)'),
  (73, 'Tamburi', 'Enterolobium contortisiliquum', 'Fabaceae', 'Magnoliopsida', 'Menos Preocupante (LC)'),
  (74, 'Babosa', 'Aloe vera', 'Asphodelaceae', 'Liliopsida', 'Não Avaliado (NE)'),
  (75, 'Barriguda', 'Ceiba glaziovii', 'Malvaceae', 'Magnoliopsida', 'Menos Preocupante (LC)'),
  (76, 'Pombo / Pombo-doméstico', 'Columba livia', 'Columbidae', 'Aves', 'Pouco Preocupante (LC)'),
  (77, 'Arara-azul-de-lear', 'Anodorhynchus leari', 'Psittacidae', 'Aves', 'Em Perigo (EN)'),
  (78, 'Soim / Sagui-do-nordeste', 'Callithrix jacchus', 'Callitrichidae', 'Mammalia', 'Pouco Preocupante (LC)'),
  (79, 'Espada-de-São-Jorge', 'Dracaena-trifasciata', 'Asparagaceae', 'Liliopsida', 'Não avaliado'),
  (80, 'Planta-zebra', 'Tradescantia-zebrina', 'Commelinaceae', 'Liliopsida', 'Não avaliado'),
  (81, 'Flamboyant', 'Delonix regia', 'Fabaceae', 'Magnoliopsida', 'Não avaliado'),
  (82, 'Barriguda', 'Ceiba-glaziovii', 'Malvaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (83, 'Algaroba', 'Prosopis-juliflora', 'Fabaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (84, 'Joaninha', 'Charidotella-sexpunctata', 'Coccinellidae', 'Insecta', 'Pouco preocupante'),
  (85, 'Gato-doméstico', 'Felis-catus', 'Felidae', 'Mammalia', 'Não avaliado'),
  (86, 'Pereiro', 'Pyrus-communis', 'Rosaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (87, 'Palma', 'Opuntia-ficus-indica', 'Cactaceae', 'Magnoliopsida', 'Pouco preocupante'),
  (88, 'mandacaru', 'Cereus-jamacaru', 'Cactaceae', 'Magnoliopsida', 'Sofre grande pressão ambiental');

INSERT INTO public.regioes (id, nome, tipo_ecossistema, latitude, longitude, descricao)
VALUES
  (1, 'Local de observação – Barriguda', 'Caatinga', 463263, 846240, 'Local onde a espécie Barriguda foi observada.'),
  (2, 'Local de observação – Mandacaru', 'Caatinga', 4632229, 8846239, 'Local onde a espécie Mandacaru foi observada.'),
  (3, 'Local de observação – Umbuzeiro', 'Caatinga', 463328, 8846188, 'Local onde a espécie Umbuzeiro foi observada.'),
  (4, 'Local de observação – Araçá', 'Caatinga', 4633330, 8846327, 'Local onde a espécie Araçá foi observada.'),
  (5, 'Local de observação – Siriguela', 'Caatinga', 463308, 8846222, 'Local onde a espécie Siriguela foi observada.'),
  (6, 'Local de observação – Eucalipto', 'Caatinga', 464487, 8845947, 'Local onde a espécie Eucalipto foi observada.'),
  (7, 'Local de observação – Catingueira', 'Caatinga', 463773, 8845640, 'Local onde a espécie Catingueira foi observada.'),
  (8, 'Local de observação – Juazeiro', 'Caatinga', 464191, 8842177, 'Local onde a espécie Juazeiro foi observada.'),
  (9, 'Local de observação – Espada-de-São-Jorge', 'Caatinga', 46337, 8846106, 'Local onde a espécie Espada-de-São-Jorge foi observada.'),
  (10, 'Local de observação – Algaroba', 'Caatinga', 463340, 8846232, 'Local onde a espécie Algaroba foi observada.'),
  (11, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536648, -38.997590, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (12, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536924, -38.997843, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (13, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536809, -38.997765, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (14, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536712, -38.997650, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (15, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.537069, -38.997869, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (16, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.537131, -38.998021, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (17, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536648, -38.997590, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (18, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536850, -38.997720, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (19, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536781, -38.997694, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (20, 'IFBA, de Euclides da Cunha', 'Ambiente terrestre antropizado', -10.536735, -38.997812, 'Área verde do campus do IFBA, com plantas ornamentais, árvores, arbustos e vegetação rasteira, próxima a áreas construídas e espaços de circulação'),
  (21, 'Área aberta do IFBA Campus Euclides da Cunha', 'Área verde urbana/escolar inserida no bioma Caatinga', -10.537300, -38.997817, 'Área aberta com vegetação rasteira e fluxo humano alto.'),
  (22, 'Caldas do Jorro', 'Área doméstica/urbana inserida no bioma Caatinga', -11.034760, -38.796060, 'Jardim conservado com variedade de espécies de flora.'),
  (23, 'Jardim residencial', 'Ambiente doméstico/urbano inserido no bioma Caatinga', -10.438800, -39.327283, 'Jardim residencial localizado em uma área de Caatinga. Euclides da Cunha (BA).'),
  (24, 'Jardim da Pousada Recanto dos Pássaros em Caldas do Jorro', 'Ambiente doméstico/urbano inserido no bioma Caatinga', -11.03758477, -38.79331723, 'Jardim localizado em uma área de Caatinga. Caldas do Jorro - Tucano (BA).'),
  (25, 'Área vegetativa em Tucano BA', 'Ambiente urbano natural', -10.98238355, -38.79782250, 'Jardim localizado em uma área de Caatinga. Caldas do Jorro - Tucano (BA).'),
  (26, 'Casa em Monte Santo', 'Área residencial urbana', -10.433032, -39.325689, 'Área residencial com presença de vegetação cultivada e circulação de moradores.'),
  (27, 'Quijingue, Bahia', 'Ambiente urbano doméstico, Caatinga', 477646, 8811816, 'Quintal doméstico.'),
  (28, 'IFBA Campus Euclides da Cunha', 'Floresta subtropical', 477654, 8811814, 'Área grande externa com diversas espécies de plantas.'),
  (29, 'IFBA Campus Euclides da Cunha', 'Floresta subtropical', 500229, 8835235, 'Jardim médio interno e decorativo.'),
  (30, 'IFBA Campus Euclides da Cunha', 'Ambiente escolar, Caatinga', 500250, 8835214, 'Área grande externa com diversas espécies de plantas.'),
  (31, 'IFBA Campus Euclides da Cunha', 'Ambiente ecolar, Caatinga', 500315, 8835222, 'Área grande externa com diversas espécies de plantas.'),
  (32, 'IFBA Campus Euclides da Cunha', 'Ambiente escolar, Caatinga', 500314, 8835228, 'Área grande externa com diversas espécies de plantas.'),
  (33, 'IFBA Campus Euclides da Cunha', 'Ambiente escolar, Caatinga', 500321, 8835226, 'Área grande externa com diversas espécies de plantas.'),
  (34, 'IFBA Campus Euclides da Cunha', 'Ambiente escolar, Caatinga', 500348, 8835240, 'Área grande externa com diversas espécies de plantas'),
  (35, 'IFBA Campus Euclides da Cunha', 'Ambiente terrestre escolar, Caatinga', 500239, 8835220, 'Área grande externa com diversas espécies de plantas.'),
  (36, 'Distrito de Aribicé - Euclides da Cunha', 'Ambiente terrestre urbano/domestico, Caatinga', 522643, 8833395, 'Área de quintal doméstico, espaço pequeno.'),
  (37, 'Chapada do Araripe - Ceará', 'Floresta úmida e Caatinga', -7.33308, -39.41221, 'Região de ocorrência do Soldadinho-do-Araripe.'),
  (38, 'Caatinga do Nordeste', 'Caatinga', -10.184, -38.045, 'Área representativa do bioma Caatinga.'),
  (39, 'Parque Nacional Serra da Capivara', 'Caatinga', -8.8086957, -42.6291961, 'Parque localizado no estado do Piauí, com grande diversidade natural e arqueológica.'),
  (40, 'Parque Nacional do Catimbau', 'Caatinga e Cerrado', -8.515563, -37.225917, 'Unidade de conservação localizada em Pernambuco.'),
  (41, 'Chapada Diamantina', 'Cerrado e campos rupestres', -12.8827431, -41.373114, 'Região com grande diversidade de espécies e diferentes formações vegetais.'),
  (42, 'Curaçá - Bahia', 'Caatinga', -8.992821, -39.906749, 'Região do sertão baiano com vegetação típica da Caatinga.'),
  (43, 'Vale do Rio São Francisco', 'Caatinga e ambientes de água doce', -9.3986, -40.5089, 'Região próxima ao Rio São Francisco.'),
  (44, 'Parque Estadual Juquery', 'Cerrado', -23.3644, -46.7328, 'Área de conservação localizada no estado de São Paulo.'),
  (45, 'Reserva Natural Serra das Almas', 'Caatinga', -5.14, -40.904, 'Área protegida localizada na região da Caatinga.'),
  (46, 'Ilha do Cajual - Alcântara, Maranhão', 'Zona costeira e sítio paleontológico', -2.47292, -44.48071, 'Localidade conhecida por seus registros paleontológicos.'),
  (47, 'Jaborandi - Bahia', 'Cerrado', -13.52806, -44.42139, 'Município baiano localizado em área de transição e ocorrência de espécies do Cerrado.'),
  (48, 'Petrolina - Pernambuco', 'Caatinga', -9.389, -40.503, 'Município localizado no sertão de Pernambuco, às margens do Rio São Francisco.'),
  (49, 'Parque Nacional da Serra da Canastra', 'Cerrado', -20.2500, -46.5000, 'Unidade de conservação localizada no sudoeste de Minas Gerais, caracterizada por relevo montanhoso e nascentes de rios importantes como o São Francisco.'),
  (50, 'Estação Ecológica do Taim', 'Pampa', -32.5333, -52.5333, 'Área protegida localizada no sul do Rio Grande do Sul, formada por ambientes de banhados, lagoas, campos e dunas.'),
  (51, 'Parque Nacional das Sete Cidades', 'Caatinga e Cerrado', -4.0996346, -41.6989054, 'Área protegida no estado do Piauí, conhecida por suas formações rochosas e pinturas rupestres.'),
  (52, 'Quijingue', 'Caatinga', -10.7520, -39.2090, 'Área de vegetação de Caatinga onde ocorrem espécies típicas do semiárido nordestino.'),
  (53, 'Licuri (Serra da Onça)', 'Caatinga', -10.95332378, -39.09308899, NULL),
  (54, 'Palmatória', 'Caatinga', -10.95336898, -39.09317138, NULL),
  (55, 'Jurema-branca', 'Caatinga', -10.95340526, -39.09282360, NULL),
  (56, 'Aroeira', 'Caatinga', -10.95340531, -39.09265886, NULL),
  (57, 'Caroá', 'Caatinga', -10.95340531, -39.09265886, NULL),
  (58, 'Gravatá', 'Caatinga', -10.95531422, -39.09057269, NULL),
  (59, 'Imburana-de-cheiro', 'Caatinga', -10.95343253, -39.09237514, NULL),
  (60, 'Cedro-rosa', 'Caatinga', -10.95607411, -39.08995055, NULL),
  (61, 'Barriguda', 'Caatinga', -10.95590222, -39.09010609, NULL),
  (62, 'Inco', 'Caatinga', -10.95572132, -39.09018841, NULL),
  (63, 'Jeremoabo', 'Caatinga', -9.922217, -38.760300, 'Região de clima quente e seco, com chuvas irregulares e vegetação de Caatinga adaptada à escassez de água.'),
  (64, 'Canudos', 'Caatinga', -9.870183, -38.985000, 'Região de Caatinga, de clima semiárido, com altas temperaturas, chuvas irregulares e vegetação adaptada à escassez de água.'),
  (65, 'Canudos', 'Caatinga', -9.869150, -38.989750, 'Região semiárida da Caatinga, caracterizada por clima quente e seco, chuvas irregulares e vegetação adaptada à escassez de água.'),
  (66, 'Canudos', 'Caatinga', -9.898500, -39.031233, 'Área com grande diversidade de flora na região da Caatinga.'),
  (67, 'Jeremoabo', 'Caatinga', -9.922033, -38.760567, 'Região semiárida da Caatinga, com clima quente e seco, chuvas irregulares e vegetação adaptada à escassez de água.'),
  (68, 'Jeremoabo', 'Caatinga', -9.922367, -38.760817, 'Região de Caatinga caracterizada pelo clima semiárido, altas temperaturas, chuvas irregulares e vegetação adaptada à seca.'),
  (69, 'Jeremoabo', 'Caatinga', -9.922017, -38.759167, 'Região semiárida da Caatinga, com clima quente e seco, baixa disponibilidade de água e vegetação adaptada às condições de seca.'),
  (70, 'Jeremoabo', 'Caatinga', -9.922567, -38.758767, 'Região de Caatinga do semiárido nordestino, com clima quente e seco e espécies vegetais adaptadas à escassez de água.'),
  (71, 'Jeremoabo', 'Caatinga', -9.922117, -38.760833, 'Região semiárida de Caatinga, marcada por altas temperaturas, chuvas irregulares e vegetação adaptada ao clima seco.'),
  (72, 'Canudos', 'Caatinga', -9.875150, -38.981900, 'Região de Caatinga do semiárido, com clima quente e seco, chuvas irregulares e vegetação adaptada à escassez de água.'),
  (73, 'Quijingue - Pé de Umbu', 'Caatinga / Rural', -10.774212, -39.207121, 'Área rural e aberta do semiárido, com solo exposto, vegetação esparsa e presença de árvores adaptadas ao clima seco.'),
  (74, 'Monte Santo - Tamburi', 'Área escolar / Urbana', -10.437887, -39.334990, 'Área de escola, em pátio ou pequeno espaço arborizado, com algumas árvores e vegetação no ambiente.'),
  (75, 'IFBA - Euclides da Cunha - Mandacaru', 'Caatinga / Área escolar', -10.537059, -38.997781, 'Área externa do IFBA, com gramado, pavimentação e vegetação utilizada no espaço escolar.'),
  (76, 'IFBA - Euclides da Cunha - Pé de Licuri', 'Caatinga / Área escolar', -10.536591, -38.997564, 'Área verde do IFBA, com gramado e vegetação cultivada presente no espaço escolar.'),
  (77, 'IFBA - Euclides da Cunha - Algaroba', 'Caatinga / Área escolar', -10.753893, -39.213110, 'Área com solo exposto e vegetação esparsa, próxima a áreas residenciais.'),
  (78, 'IFBA - Euclides da Cunha - Babosa', 'Caatinga / Área escolar', -10.536602, -38.998422, 'Área de jardim do IFBA, próxima a muro, gramado, solo exposto e outras plantas.'),
  (79, 'IFBA - Euclides da Cunha - Três Marias', 'Caatinga / Área escolar', -10.536974, -38.997203, 'Área de jardim do IFBA, próxima a pavimentação, postes e outras plantas ornamentais.'),
  (80, 'Algodões - Quijingue - Barriguda', 'Caatinga / Povoado', -10.677041, -39.052110, 'Área aberta do povoado de Algodões, com solo seco, vegetação esparsa e construções próximas.'),
  (81, 'Açude da Lagoinha das Pedras', 'Caatinga / Ambiente aquático', -10.726256, -39.214628, 'Corpo de água localizado em ambiente semiárido, com vegetação ao redor e áreas de solo exposto.'),
  (82, 'Açude do Rabelo', 'Caatinga / Ambiente aquático', -10.744932, -39.198013, 'Reservatório localizado em ambiente semiárido, com vegetação esparsa e áreas de solo seco ao redor.'),
  (83, 'Residência', 'Doméstico / Urbano', -10.774203, -39.207115, 'Ambiente residencial urbano onde foi realizada a observação do cão doméstico.'),
  (84, 'Banzaê', 'Semiárido da Caatinga', 5.4318456, 88.3214237, 'Área de conservação com grande diversidade de fauna e flora.'),
  (85, 'Banzaê', 'Semiárido da Caatinga', 5.4318636, 88.3212394, 'Área de conservação com grande diversidade de fauna e flora.'),
  (86, 'Banzaê', 'Semiárido da Caatinga', 5.4322227, 88.3212073, 'Área de conservação com grande diversidade de fauna e flora.'),
  (87, 'Banzaê', 'Semiárido da Caatinga', 5.4315357, 88.3214793, 'Área de conservação com grande diversidade de fauna e flora.'),
  (88, 'Banzaê', 'Semiárido da Caatinga', 5.4317488, 88.3210293, 'Área de conservação com grande diversidade de fauna e flora.'),
  (89, 'Banzaê', 'Semiárido da Caatinga', 5.4316073, 88.3204288, 'Área de conservação com grande diversidade de fauna e flora.'),
  (90, 'Banzaê', 'Semiárido da Caatinga', 5.4319541, 88.3201573, 'Área de conservação com grande diversidade de fauna e flora.'),
  (91, 'Banzaê', 'Semiárido da Caatinga', 5.4271703, 88.3009004, 'Área de conservação com grande diversidade de fauna e flora.'),
  (92, 'Banzaê', 'Semiárido da Caatinga', 5.4261151, 88.3008667, 'Área de conservação com grande diversidade de fauna e flora.'),
  (93, 'Banzaê', 'Semiárido da Caatinga', 5.4255992, 88.3029556, 'Área de conservação com grande diversidade de fauna e flora.'),
  (94, 'Quintal de uma casa em Monte Santo - BA', 'Ambiente urbano/doméstico', -10.435385, -39.3326270, 'Quintal de uma casa onde a espada-de-São-Jorge foi plantada.'),
  (95, 'Casa em Monte Santo - BA', 'Ambiente urbano/doméstico', -10.435196, -39.3317310, 'Casa onde a planta-zebra foi observada.'),
  (96, 'Rua em Monte Santo - BA', 'Ambiente urbano', -10.414494, -39.3317640, 'Rua onde o flamboyant foi observado.'),
  (97, 'Monte Santo', 'Caatinga', -10.437987, -39.3351050, 'Centro de Lazer'),
  (98, 'Monte Santo', 'Caatinga', -10.437987, -39.3351050, 'Centro de Lazer'),
  (99, 'Quijingue', 'Caatinga', -10.752530, -39.2150290, 'Quintal residencial com presença de vegetação'),
  (100, 'Quintal em Lagoa dos Cágados - Quijingue/BA', 'Ambiente urbano/doméstico', -10.761530, -39.0773070, 'Área residencial com quintal e jardim onde o animal foi observado.'),
  (101, 'Povoado Terra Branca', 'Caatinga', -10.851492, -39.3809550, 'Área de roça'),
  (102, 'Povoado Terra Branca', 'Caatinga', -10.851492, -39.3809550, 'Área de roça'),
  (103, 'IFBA', 'Ambiente institucional que tem alguma preservação das espécies da Caatinga', -10.536601, -38.9968650, 'Área institucional');

INSERT INTO public.observacoes (id, data, descricao, foto_url, especie_id, regiao_id)
VALUES
  (1, '2026-07-22', 'Barriguda observada na região.', 'https://drive.google.com/file/d/1eeb7B0UjkeuHG2_3jW1LOS6FsnCBnT8Z/view?usp=drivesdk', 1, 1),
  (2, '2026-07-22', 'Mandacaru observada na região.', 'https://drive.google.com/file/d/1sBlSb3lS3idJHS00P2uK4tw50BcJrzfg/view?usp=drivesdk', 2, 2),
  (3, '2026-07-22', 'Umbuzeiro observada na região.', 'https://drive.google.com/file/d/1snRWeiMK-g1oYNKY8a-j-pXDV1KgMW9y/view?usp=drivesdk', 3, 3),
  (4, '2026-07-22', 'Araçá observada na região.', 'https://drive.google.com/file/d/1OPiQ2slXDGqkgwvVvvpU-kA7m2q7krAZ/view?usp=drivesdk', 4, 4),
  (5, '2026-07-22', 'Siriguela observada na região.', 'https://drive.google.com/file/d/1GNlDLAjxq7PdYq5W3uCVMNwXCCIWL3VR/view?usp=drivesdk', 5, 5),
  (6, '2026-07-22', 'Eucalipto observado na região.', 'https://drive.google.com/file/d/10B-EIl7M5ijR8z13N0nbeVxjquzLnivA/view?usp=drivesdk', 6, 6),
  (7, '2026-07-22', 'Catingueira observada na região.', 'https://drive.google.com/file/d/17n0rmFgWpq-tTyCioloAExhSeCOoKFEQ/view?usp=drivesdk', 7, 7),
  (8, '2026-07-22', 'Juazeiro observado na região.', 'https://drive.google.com/file/d/1aMF-B5M4Lf5rwNM2haAmRUjmPl_2fcyB/view?usp=drivesdk', 8, 8),
  (9, '2026-07-22', 'Espada-de-São-Jorge observada na região.', NULL, 9, 9),
  (10, '2026-07-22', 'Algaroba observada na região.', 'https://drive.google.com/file/d/1YAbrq3qOcoqA3b0EGGo8YEyDNjYO5QHe/view?usp=drivesdk', 10, 10),
  (11, '2026-07-15', 'Foi observada uma planta com folhas compridas e pontudas, próxima à vegetação do local.', 'https://drive.google.com/file/d/1nb6ZGygtU1Q8xHd7fRiPjZIm1AlLt2gN/view?usp=drivesdk', 11, 11),
  (12, '2026-07-15', 'Foi observada uma planta baixa, com estruturas verdes achatadas, localizada em uma área aberta.', 'https://drive.google.com/file/d/1eQrNcuuyARSS7UrmsYjiLXBS87JHzWSZ/view?usp=drivesdk', 12, 12),
  (13, '2026-07-15', 'Foi observado um coqueiro alto, com folhas concentradas na parte superior e localizado em uma área aberta.', 'https://drive.google.com/file/d/1hqS-Z-wK1tlSCAJWP4WrfjKx-yuXPosA/view?usp=drivesdk', 13, 13),
  (14, '2026-07-15', 'Foi observada uma planta verde, alta e com vários galhos, localizada em uma área aberta.', 'https://drive.google.com/file/d/1YWNmydPyAm_4LFnk18sBu4xIS3ibv7z0/view?usp=drivesdk', 2, 14),
  (15, '2026-07-15', 'Foi observada uma palmeira com muitas folhas finas e compridas, em meio à vegetação.', 'https://drive.google.com/file/d/1OqoHN4SFuVyJp5m8kC4IyQI9RSYGA5OV/view?usp=drivesdk', 14, 15),
  (16, '2026-07-15', 'Foi observada uma árvore de tamanho médio, com bastante folhagem verde e vários galhos.', 'https://drive.google.com/file/d/1uo7Xy-ARtEAr0FwZJnaQS6AYoO9dVaN-/view?usp=drivesdk', 15, 16),
  (17, '2026-07-15', 'Foi observada uma árvore com copa formada por folhas largas, presente na área externa.', 'https://drive.google.com/file/d/1gW5kGC4oN1BpYvvAX_ZVYnVOnRNAm7o2/view?usp=drivesdk', 16, 17),
  (18, '2026-07-15', 'Foi observado um mamoeiro com caule fino e folhas grandes e recortadas. A planta estava em uma área aberta, junto à vegetação do local.', 'https://drive.google.com/file/d/13LJlFlFBJsyY1GowEwaQ9HKvJM6Nd1FK/view?usp=drivesdk', 17, 18),
  (19, '2026-07-15', 'Foi observado um tomateiro de pequeno porte, com caule fino, folhas verdes e vários galhos.', 'https://drive.google.com/file/d/1S3kCltJcdbNDhhLB5qLtH-P-kzCBQipy/view?usp=drivesdk', 18, 19),
  (20, '2026-07-15', 'Foi observada uma bananeira com folhas grandes, largas e verdes, formando uma vegetação bem visível no local.', 'https://drive.google.com/file/d/1LU4tV20hQIkfQaMfEfMDLnFVis-ycd8f/view?usp=drivesdk', 19, 20),
  (21, '2026-05-26', 'Piolho-de-cobra observado no solo de uma área aberta do IFBA Campus Euclides da Cunha, entre restos de vegetação seca.', 'https://drive.google.com/file/d/1-eeyWs7StMxKWtWQw15EEoEVzF_KA-yX/view?usp=sharing', 20, 21),
  (22, '2026-03-10', 'Oliveira observada em um jardim.', 'https://drive.google.com/file/d/1P8HPcVSbiEzQLAXM4KRqsPO_d-4-D1Qf/view?usp=drivesdk', 21, 22),
  (23, '2026-05-20', 'Alamanda roxa observada em uma área aberta do IFBA Campus Euclides da Cunha, apresentando flores de coloração roxa e folhas verdes.', 'https://ibb.co/M5hvbYfG', 22, 21),
  (24, '2026-05-15', 'Rosa do Deserto observada em um jardim residencial, apresentando flores rosadas e folhas verdes, cultivada em local com bastante luz solar.', 'https://ibb.co/tM28kSPK', 23, 23),
  (25, '2026-07-16', 'Bananeira observada em uma área vegetativa cultivada', 'https://drive.google.com/file/d/1IinH_mZOnuzWfhJVic6EsZXiSbCfSeJ5/view?usp=drivesdk', 24, 21),
  (26, '2026-07-15', 'Palmeira-de-natal observada em uma área vegetativa cultivada', 'https://drive.google.com/file/d/1h9mMi5Aruy3khRHVzcrP4yU8fjjXT19V/view?usp=drivesdk', 25, 24),
  (27, '2026-07-15', 'Mandacaru observado em uma área vegetativa em Tucano - BA', 'https://drive.google.com/file/d/1NnO07XRrl6QLr5TavktMCBbTWICvzMhI/view?usp=drivesdk', 2, 25),
  (28, '2026-09-16', 'Pau-brasil observado em uma casa localizada no município de Monte Santo.', 'https://novamata.org/wp-content/uploads/2023/10/pau-brasil-tronco-1.jpg', 26, 26),
  (29, '2026-07-16', 'Mangueira observada em uma área de vegetação cultivada.', 'https://docs.google.com/document/d/1d1pMCAVZm8w8IrQGk9qynxhKx5RVlvbLxEOkpUHKBgY/edit?usp=drivesdk', 27, 21),
  (30, '2026-07-16', 'Mamoeiro observado em uma área de vegetação cultivada.', 'https://docs.google.com/document/d/1lvI7aKT4LWwiffWxd-QNci0zi5lhExSf_m8v4pqSYio/edit?usp=drivesdkp', 28, 21),
  (31, '2026-09-12', 'Goiabeira observada no hall de entrada de uma casa.', 'https://drive.google.com/file/d/1WdQGPdLhLlDyJAF_5PknOg7bf3sbDCKB/view?usp=drive_link', 29, 27),
  (32, '2026-07-15', 'Mangueira observada durante o intervalo escolar.', 'https://drive.google.com/file/d/1XBSFQDrE9aLaJabpZaef1PRJrVtt1nJx/view?usp=drive_link', 29, 27),
  (33, '2026-07-15', 'Pé de Licuri observado durante o intervalo escolar.', 'https://drive.google.com/file/d/1J2isJQQEdGvfk5ZughVrtrZLaDhpPZAb/view?usp=drive_link', 29, 27),
  (34, '2026-07-15', 'Primavera observada durante o intervalo escolar', 'https://drive.google.com/file/d/1YDfjevEihAXe0PA2_prV5Zmx3zpFBbyM/view?usp=drive_link', 29, 27),
  (35, '2026-07-15', 'Mamoeiro observado por baixo durante o intervalo escolar.', 'https://drive.google.com/file/d/1ZujJgacWsM43AsMiiKtLP_OkWAni7gkg/view?usp=drive_link', 29, 27),
  (36, '2026-08-15', 'Tomateiro observado durante o intervalo escolar.', 'https://drive.google.com/file/d/1Dn79WwDm7XYRP2VSAf2eSxRUJLzpZYtn/view?usp=drive_link', 29, 27),
  (37, '2026-07-15', 'Tomateiro próximo ao estacionamente, observado durante o intervalo escolar.', 'https://drive.google.com/file/d/1jb05S5_bhHpkawoRnLAvJJdmQvLGc0_3/view?usp=drive_link', 29, 27),
  (38, '2026-08-15', 'Coqueiro observado próximo à quadra durante o intervalo escolar.', 'https://drive.google.com/file/d/1Wh0yU2vTqUuhZlzg8Y8IP4EBYwQSR6cR/view?usp=drive_link', 29, 27),
  (39, '2026-07-15', 'Pé de Licuri próximo à quadra observado durante o intervalo escolar.', 'https://drive.google.com/file/d/1G4bPcyYcXCb2hQR3zo6-EaYRrCmHVwG8/view?usp=drive_link', 29, 27),
  (40, '2026-09-12', 'Jabuticabeira observada no quintal de uma casa de vó.', 'https://drive.google.com/file/d/1YyXmXBNU1ldlgyAs5HtPthnOtV7bPiRg/view?usp=drive_link', 29, 27),
  (41, '2026-09-06', 'Registro do Soldadinho-do-Araripe.', 'https://pt.wikipedia.org/wiki/Soldadinho-do-araripe', 33, 37),
  (42, '2026-09-11', 'Registro do Guigó-de-Caatinga.', 'https://pt.wikipedia.org/wiki/Callicebus_barbarabrownae', 34, 38),
  (43, '2026-09-13', 'Registro do Cágado-do-Nordeste.', 'https://pt.wikipedia.org/wiki/Mesoclemmys_tuberculata', 35, 43),
  (44, '2026-09-07', 'Registro da Jararaca-da-seca.', 'https://pt.wikipedia.org/wiki/Bothrops_erythromelas', 36, 38),
  (45, '2016-07-07', 'Registro do Jabuti-piranga.', 'https://pt.wikipedia.org/wiki/Chelonoidis_carbonarius', 37, 39),
  (46, '2019-08-07', 'Registro do Periquito-da-Caatinga.', 'https://pt.wikipedia.org/wiki/Eupsittula_cactorum', 38, 38),
  (47, '2023-05-02', 'Registro do Carcará.', 'https://pt.wikipedia.org/wiki/Caracara_plancus', 39, 38),
  (48, '2000-11-10', 'Imagem de exemplar preservado em coleção de museu.', 'https://pt.wikipedia.org/wiki/Ararinha-azul', 40, 39),
  (49, '2025-10-21', 'Registro do Teiú.', 'https://commons.wikimedia.org/wiki/Salvator_merianae', 41, 40),
  (50, '2016-05-26', 'Registro do Tatu-bola-do-Nordeste.', 'https://commons.wikimedia.org/wiki/Tolypeutes_tricinctus', 42, 47),
  (51, '2020-08-21', 'Registro do Preá.', 'https://commons.wikimedia.org/wiki/Cavia_aperea', 43, 38),
  (52, '2025-06-23', 'Registro relacionado ao Oxalaia quilombensis.', 'https://share.google/6qVC0F3TJdfr7Wgl0', 53, 46),
  (53, '2021-12-21', 'Registro relacionado ao Umbuzeiro.', 'https://share.google/GSkLFmyM9sMu86bwK', 3, 48),
  (54, '2026-09-04', 'Calango-de-cauda-verde observado no Vale do Rio São Francisco.', 'CalangodeCaudaVerde|NomeCientífico:Ameivaameiva', 44, 43),
  (55, '2026-09-04', 'Cascavel observada no Parque Estadual Juquery.', 'https://share.google/images/62ZFJ8xf13JcE0iaT', 45, 44),
  (56, '2026-09-04', 'Veado-catingueiro observado na Reserva Natural Serra das Almas.', 'https://share.google/images/B05nwRTI1eOnQKhHB', 46, 45),
  (57, '2026-09-05', 'Asa-branca observada em voo durante o período matutino.', 'https://share.google/images/xb6l5idM8SleT7fXt', 47, 38),
  (58, '2026-09-10', 'Tamanduá-bandeira capturado em câmera de armadilha durante a noite.', 'https://share.google/images/fD6P6DAfcI3gLy7Cr', 50, 45),
  (59, '2026-09-11', 'Mandacaru registrado em área de Caatinga semiárida.', 'https://pt.wikipedia.org/wiki/Cereus_jamacaru', 2, 52),
  (60, '2026-09-13', 'Xique-xique registrado em área de Caatinga semiárida.', 'https://pt.wikipedia.org/wiki/Pilosocereus_gounellei', 51, 52),
  (61, '2026-09-07', 'Catingueira registrada em área de vegetação nativa da Caatinga.', 'https://pt.wikipedia.org/wiki/Poincianella_pyramidalis', 7, 52),
  (62, '2026-09-15', 'Juazeiro registrado em área de vegetação de Caatinga.', 'https://pt.wikipedia.org/wiki/Ziziphus_joazeiro', 52, 52),
  (63, '2026-07-20', 'Exemplar de Licuri observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/licuri.jpg', 14, 53),
  (64, '2026-07-20', 'Exemplar de Palmatória observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/palmatoria.jpg', 54, 54),
  (65, '2026-07-20', 'Exemplar de Jurema-branca observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/jurema_branca.jpg', 55, 55),
  (66, '2026-07-20', 'Exemplar de Aroeira observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/aroeira.jpg', 56, 56),
  (67, '2026-07-20', 'Exemplar de Caroá observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/caroa.jpg', 57, 57),
  (68, '2026-07-20', 'Exemplar de Gravatá observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/gravata.jpg', 58, 58),
  (69, '2026-07-20', 'Exemplar de Imburana-de-cheiro observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/imburana.jpg', 59, 59),
  (70, '2026-07-20', 'Exemplar de Cedro-rosa observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/cedro_rosa.jpg', 60, 60),
  (71, '2026-07-20', 'Exemplar de Barriguda observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/barriguda.jpg', 1, 61),
  (72, '2026-07-20', 'Exemplar de Inco observado na Serra da Onça, na Caatinga.', 'https://exemplo.com/fotos/inco.jpg', 61, 62),
  (73, '2026-07-18', 'O umbuzeiro é uma árvore típica da Caatinga, adaptada ao clima seco do Nordeste. Produz frutos chamados umbus, muito utilizados na alimentação e na produção de sucos, doces e geleias.', '...', 62, 63),
  (74, '2026-07-18', 'Cacto típico da Caatinga, com caule verde e ramificado, coberto por espinhos e adaptado às condições quentes e secas do semiárido.', '...', 63, 64),
  (75, '2026-07-18', 'Planta típica da Caatinga, com folhas longas e espinhosas, adaptada ao clima seco e às condições do semiárido.', '...', 64, 65),
  (76, '2026-07-18', 'Árvore de copa ampla, folhas verdes e ramos com espinhos, adaptada ao clima seco da Caatinga.', '...', 65, 66),
  (77, '2026-07-18', 'Árvore de pequeno porte, com folhas compostas e numerosas, adaptada a regiões de clima quente e seco.', '...', 66, 67),
  (78, '2026-07-18', 'Cacto típico da Caatinga, com caule verde e ramificado, coberto por espinhos e adaptado às condições quentes e secas do semiárido.', '...', 67, 68),
  (79, '2026-07-18', 'Árvore adaptada ao clima semiárido, com copa ampla, ramos com espinhos e capacidade de desenvolver-se em condições de pouca disponibilidade de água.', '...', 68, 69),
  (80, '2026-07-18', 'Árvore típica de regiões semiáridas, com folhas resistentes e adaptação às condições de clima quente e períodos de estiagem.', '...', 69, 70),
  (81, '2026-07-18', 'Arbusto ou pequena árvore cultivada por seus frutos avermelhados e ricos em vitamina C, adaptada a regiões de clima quente.', '...', 70, 71),
  (82, '2026-07-18', 'Palmeira típica da Caatinga, com folhas longas e rígidas, adaptada ao clima seco e importante para a alimentação e o uso tradicional das comunidades locais.', '...', 71, 72),
  (83, '2026-03-10', 'Cão doméstico de porte médio, pelagem curta e clara, quatro patas, orelhas caídas e cauda longa. Apresenta comportamento dócil e calmo, adaptado ao ambiente doméstico.', '', 72, 83),
  (84, '2026-07-20', 'Árvore de grande porte, com copa desenvolvida, folhas verdes e tronco espesso, proporcionando sombra no local.', '', 3, 73),
  (85, '2026-07-20', 'Árvore de médio a grande porte, com tronco desenvolvido e copa formada, localizada em ambiente escolar.', '', 73, 74),
  (86, '2026-07-20', 'Cacto de porte médio, com caules verdes alongados, ramificações verticais e presença de espinhos.', '', 2, 75),
  (87, '2026-07-20', 'Palmeira de porte médio, com folhas longas e arqueadas, apresentando aspecto saudável.', '', 14, 76),
  (88, '2026-07-20', 'Árvore de médio a grande porte, com copa ampla, folhas pequenas e tronco relativamente fino.', '', 10, 77),
  (89, '2026-07-20', 'Planta formada por folhas longas, grossas e pontiagudas, dispostas em roseta e com coloração verde-acinzentada.', '', 74, 78),
  (90, '2026-07-20', 'Planta ornamental de aspecto arbustivo, com flores ou brácteas de coloração roxa e copa arredondada.', '', 31, 79),
  (91, '2026-07-20', 'Árvore com tronco grosso e ramificado, poucas folhas e presença de estruturas semelhantes a frutos nos galhos.', '', 75, 80),
  (92, '2026-09-13', 'Observação de Cajueiro (Anacardium occidentale) em Banzaê.', '', 72, 84),
  (93, '2026-09-13', 'Observação de Jatobá (Hymenaea courbaril) em Banzaê.', '', 76, 85),
  (94, '2026-09-13', 'Observação de Mandacaru (Cereus jamacaru) em Banzaê.', '', 77, 86),
  (95, '2026-09-13', 'Observação de Laranjeira (Citrus sinensis) em Banzaê.', '', 78, 87),
  (96, '2026-09-13', 'Observação de Pau-brasil (Paubrasilia echinata) em Banzaê.', '', 72, 88),
  (97, '2026-09-13', 'Observação de Dendezeiro (Elaeis guineensis) em Banzaê.', '', 76, 89),
  (98, '2026-09-13', 'Observação de Mangueira (Mangifera indica) em Banzaê.', '', 77, 90),
  (99, '2026-09-13', 'Observação de Umbuzeiro (Spondias tuberosa) em Banzaê.', '', 78, 91),
  (100, '2026-09-13', 'Observação de Jurema-preta (Mimosa tenuiflora) em Banzaê.', '', 72, 92),
  (101, '2026-09-13', 'Observação de Pau-ferro (Libidibia ferrea) em Banzaê.', '', 76, 93),
  (102, '2026-08-14', 'Espada-de-São-Jorge observada em um quintal de uma casa em Monte Santo.', NULL, 79, 94),
  (103, '2026-08-14', 'Planta-zebra observada em uma casa em Monte Santo.', NULL, 80, 95),
  (104, '2026-08-14', 'Flamboyant observado em uma rua em Monte Santo.', NULL, 81, 96),
  (105, '2026-07-01', 'A barriguda é uma árvore de médio a grande porte conhecida pelo seu tronco bastante engrossado na parte inferior.', NULL, 82, 97),
  (106, '2026-07-01', 'A barriguda é conhecida pelo seu tronco grosso que parece uma barriga', NULL, 83, 98),
  (107, '2025-10-19', 'Besouro de pequeno porte com carapaça arredondada e de coloração dourada.', NULL, 84, 99),
  (108, '2026-03-03', 'Gato doméstico fêmea observado no quintal, porte médio, pelagem clara com manchas escuras e olhos azuis.', NULL, 85, 100),
  (109, '2026-07-12', 'Observado em Terra Branca', NULL, 86, 101),
  (110, '2026-07-28', 'Observado em Terra Branca', NULL, 87, 102),
  (111, '2026-09-11', 'Observado no Campus IFBA de Euclides', NULL, 88, 103);

SELECT setval(pg_get_serial_sequence('public.especies', 'id'), COALESCE((SELECT MAX(id) FROM public.especies), 1), true);
SELECT setval(pg_get_serial_sequence('public.regioes', 'id'), COALESCE((SELECT MAX(id) FROM public.regioes), 1), true);
SELECT setval(pg_get_serial_sequence('public.observacoes', 'id'), COALESCE((SELECT MAX(id) FROM public.observacoes), 1), true);
COMMIT;