import { ArrowLeft, Info, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../app/providers/AuthProvider';
import { PhotoUploader } from '../../components/activities/PhotoUploader';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { IconButton } from '../../components/ui/IconButton';
import { ErrorState, LoadingState } from '../../components/ui/States';
import { activityService } from '../../services/activityService';
import { agendaService } from '../../services/agendaService';
import type { Occurrence, SubmissionPhoto } from '../../types/domain';
import { formatLongDate, formatTime } from '../../utils/format';

export function ActivityPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const [occurrence, setOccurrence] = useState<Occurrence | null>(null); const [note, setNote] = useState(''); const [files, setFiles] = useState<File[]>([]); const [savedPhotos, setSavedPhotos] = useState<SubmissionPhoto[]>([]); const [deletingPhoto, setDeletingPhoto] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<'draft' | 'submit' | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([agendaService.get(id), activityService.getDraft(id)]).then(([item, draft]) => { setOccurrence(item); setNote(draft?.note ?? ''); setSavedPhotos(draft?.photos ?? []); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, [id]);
  const save = async (submit: boolean) => { if (!user || !occurrence) return; if (submit && occurrence.rule.requires_evidence && files.length + savedPhotos.length === 0) { setError('Adicione ao menos uma foto antes de enviar esta atividade.'); return; } setSaving(submit ? 'submit' : 'draft'); setError(null); try { await activityService.save(occurrence.id, user.id, note, files, submit); navigate('/hoje', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar.'); } finally { setSaving(null); } };
  if (loading) return <LoadingState />; if (error && !occurrence) return <ErrorState message={error} />; if (!occurrence) return <ErrorState message="Atividade não encontrada." />;
  return <div className="space-y-section"><header className="flex items-center gap-2"><IconButton onClick={() => navigate(-1)} aria-label="Voltar"><ArrowLeft className="size-5" /></IconButton><h1 className="text-xl font-bold">Registrar atividade</h1></header><Card className="shadow-none"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{occurrence.rule.title}</h2><p className="mt-1 text-sm text-ink-secondary">{formatLongDate(occurrence.date)}</p><p className="mt-1 text-sm text-ink-secondary">Prazo: {formatTime(occurrence.rule.deadline_time)}</p></div><Badge tone="warning">Pendente</Badge></div></Card><section><h2 className="mb-3 font-bold">Evidências</h2>{savedPhotos.length > 0 && <div className="mb-4"><p className="mb-2 text-sm font-semibold text-success">{savedPhotos.length} {savedPhotos.length === 1 ? 'foto salva' : 'fotos salvas'} neste rascunho</p><div className="grid grid-cols-3 gap-2">{savedPhotos.map((photo, index) => <div key={photo.id} className="relative aspect-square overflow-hidden rounded-xl bg-surface-muted">{photo.signed_url && <img src={photo.signed_url} alt={`Evidência salva ${index + 1}`} className="size-full object-cover" />}<IconButton type="button" disabled={deletingPhoto === photo.id} aria-label={`Remover evidência salva ${index + 1}`} className="absolute right-1 top-1 size-8 bg-black/55 text-white hover:bg-black/70" onClick={async () => { setDeletingPhoto(photo.id); setError(null); try { await activityService.deletePhoto(photo.id, photo.storage_path); setSavedPhotos((current) => current.filter((item) => item.id !== photo.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível remover a foto.'); } finally { setDeletingPhoto(null); } }}><X className="size-4" /></IconButton></div>)}</div></div>}<PhotoUploader files={files} onChange={setFiles} maxFiles={Math.max(0, 8 - savedPhotos.length)} /></section><section><label htmlFor="note" className="font-bold">Observação</label><textarea id="note" className="mt-3 min-h-28 w-full resize-none rounded-control border bg-white p-3 text-sm" placeholder="Adicione um comentário (opcional)" maxLength={300} value={note} onChange={(event) => setNote(event.target.value)} /><p className="mt-1 text-right text-xs text-ink-secondary">{note.length}/300</p></section><div className="flex gap-2 rounded-control bg-warning-soft p-3 text-sm text-warning"><Info className="mt-0.5 size-4 shrink-0" aria-hidden /><p>Após o envio, o status da atividade será <strong>Aguardando confirmação</strong>.</p></div>{error && <p role="alert" className="rounded-control bg-danger-soft p-3 text-sm text-danger">{error}</p>}<div className="space-y-2"><Button fullWidth loading={saving === 'submit'} onClick={() => save(true)}>Enviar para confirmação</Button><Button fullWidth variant="ghost" loading={saving === 'draft'} onClick={() => save(false)}>Salvar rascunho</Button></div></div>;
}
